- name: Manage software
  gather_facts: false
  become: true
  hosts: "{{ my_host }}"
  
  vars:
    - pkgname: foo
    - pkgstatus: present

  tasks:

    - name: Ensure Red Hat based OS is used
      assert:
        that: ansible_os_family == "RedHat"

    - name: Manage software on Red Hat based system
      yum:
        name: "{{ my_pkgname }}"
        state: "{{ my_pkgstatus }}"

