- name: Manage software
  gather_facts: false
  become: true
  hosts: "{{ my_host }}"
  
  tasks:

    - name: Manage software on Red Hat based system
      yum:
        name: "{{ my_pkgname }}"
        state: "{{ my_pkgstatus }}"

