- name: Configure login banners
  hosts: ios
  gather_facts: false
  
  vars:

    login_banner: !!! This system is managed by Ansible and local changes are subject to being replaced !!!

  tasks:

    - name: Ensure banner is configured on IOS devices
      notify: Ensure changes are saved 
      cisco.ios.ios_banner:
        banner: login
        text: "{{ login_banner }}" 
        state: present

  handlers:

    - name: Ensure changes are saved
      cisco.ios.ios_config:
        save_when: always
