- name: Consistent network data
  hosts: "{{ my_host | default('servera') }}"
  become: true
  gather_facts: false

  vars_files:
    - network_vars.yml

  tasks:

    #    - name: Ensure ipaddr filter is available
    #      delegate_to: localhost
    #      ansible.builtin.dnf:
    #        name: python3-netaddr
    #        state: present

    - name: Ensure /etc/hosts is correctly set
      ansible.builtin.template:
        dest: /etc/hosts
        src: hosts.j2
