---
- name: Create our bedrock world!
  hosts: all
  no_log: true
  gather_facts: true
  tasks:

    - name: Include our variables
      include_vars:
        file: encrypted_data.yml

    - name: Create users
      user:
        name: "{{ item.user }}"
        password: "{{ item.pass | password_hash('sha512') }}"
        update_password: on_create
      with_items: "{{ bedrockers }}"
