download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/rgdacosta-general-1.0.0.tar.gz
format_version: 1.0.0
name: general
namespace: rgdacosta
server: https://hub.lab.example.com/api/galaxy/content/published/
signatures: []
version: 1.0.0
version_url: /api/galaxy/content/published/v3/plugin/ansible/content/published/collections/index/rgdacosta/general/versions/1.0.0/
