#Playbook for removing client direct integration with AD
#Artur Glogowski <aglogows@redhat.com>
- hosts: replica1.lab.example.net

  vars:
    ipa_server: idm.lab.example.net
    ipa_server_ip: 172.25.250.8
    ipa_domain: lab.example.net
    ipa_realm: LAB.EXAMPLE.NET
    ipa_admin_password: RedHat123^
    ad_domain: example.net
    ad_user: Administrator
    ad_password: password123!
    ad_server_ip: 172.25.250.13

  tasks:

    - name: Leave the AD domain
      shell: realm leave {{ ad_domain }}   

    - name: Remove required packages
      yum: name={{ item }} state=absent
      with_items:
      - NetworkManager-glib
      - nm-connection-editor.x86_64
      - libsemanage-python
      - policycoreutils-python
      - realmd 
      - oddjob 
      - oddjob-mkhomedir 
      - sssd 
      - adcli 
      - krb5-workstation 
      - samba-common-tools

   
    - name: Set DNS server to AD server
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver '
        line: "nameserver {{ ipa_server_ip }}"

