# install_ipa_server.yml
# Chen Chang <cchang@redhat.com>

- hosts: idm.lab.example.net


  vars:

    ipa_domain: lab.example.net
    ipa_realm: LAB.EXAMPLE.NET
    ipa_ds_password: RedHat123^       # This is the directory manager password
    ipa_admin_password: RedHat123^    # This is the initial password for the 'admin' IPA superuser (web UI)
    ipa_server_packages:
      - ipa-server
      - ipa-server-dns
    ipa_firewalld_services:
      - freeipa-ldap
      - freeipa-ldaps

  tasks:

    - name: firewalld is enabled and started
      service: 
        name: firewalld 
        state: started
        enabled: yes
      tags:
       - firewalld

    - name: Enable firewall services for IPA in public zone
      firewalld:
        service: "{{ item }}"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      with_items: "{{ ipa_firewalld_services }}"
      tags:
       - fw_service

    - name: /etc/hosts 127.0.0.1 should not resolve to FQDN
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4'
        state: present
      tags:
       - localhost

    - name: FQDN resolves to default IPv4 address in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }}\t{{ ansible_fqdn }} {{ ansible_hostname }}"
        state: present
      tags:
       - hosts

    - name: IPA server packages installed
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ ipa_server_packages }}"
      tags:
       - packages

    - name: check IPA status
      command: ipactl status
      register: ipa_status
      changed_when: false
      ignore_errors: true
      tags:
       - ipactl

    - name: Set up IPA server
      command: >
        ipa-server-install 
        --realm={{ ipa_realm }}
        --ds-password={{ ipa_ds_password }}
        --admin-password={{ ipa_admin_password }}
        --no-ntp
        --unattended
      when: ipa_status.rc == 4
      tags:
       - ipa-server-install

    - name: Get IPA "admin" user Kerberos credentials
      shell: echo {{ ipa_admin_password }} | kinit -f admin
      changed_when: false
      tags:
       - kinit

