- name: Onboard new junos devices
  hosts: junos
  gather_facts: false

  tasks:

    - name: Ensure variables are included
      when: ansible_network_os == 'junipernetworks.junos.junos'
      ansible.builtin.include_vars:
        - vars/dns.yml
        - vars/snmp.yml

    - name: Ensure tasks are included
      loop:
        - tasks/enable_netconf.yml
        - tasks/enable_dns.yml
        - tasks/enable_snmp.yml
      when: ansible_network_os == 'junipernetworks.junos.junos'
      ansible.builtin.include_tasks: "{{ item }}"
