- name: Read a remote file 
  hosts: "{{ my_host | default('localhost') }}"
  become: false
  gather_facts: false

  tasks:

    - name: Ensure remote file is read 
      register: my_data
      ansible.builtin.slurp:
        src: "{{ my_file | default('/etc/fstab') }}"

    - name: Ensure content is displayed
      ansible.builtin.debug:
        msg: "{{ my_data['content'] | b64decode | trim }}"
