- name: Manage users
  hosts: "{{ my_host | mandatory('Please set my_hosts to indicate which hosts to target') }}"
  become: true
  gather_facts: false

  tasks:

    - name: Ensure user is at state
      user:
        name: "{{ my_user | mandatory('Please set my_user to indicate the user to manage') }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_pass | default('redhat123') | password_hash('sha512') }}"
        groups: "{{ my_group | default(omit) }}"
        generate_ssh_key: "{{ my_keygen | default(false) }}"
        update_password: on_create


