- name: Populate users from a file
  hosts: "{{ my_host }}"
  gather_facts: false
  become: true    
      
  tasks:

    - name: Ensure users are at defined state 
      loop: "{{ query('lines','cat users.txt') }}"
      vars:
        my_password: "{{ lookup('password', 'credentials/' + item + ' chars=ascii_lowercase,ascii_uppercase,digits,punctuation length=16') }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | password_hash('sha512') }}"
        update_password: on_create
