---
- block:
  - name: Ensure httpd packages are installed
    yum:
      state: present
      name:
        - httpd
        - php
        - git
        - php-mysqlnd

  - name: Ensure SELinux allows httpd connections to a remote database
    seboolean:
      name: httpd_can_network_connect_db
      state: true
      persistent: true

  - name: Ensure httpd service is started and enabled
    service:
      name: httpd
      state: started
      enabled: true

  become: true
