---
- name: Create users in the appropriate groups
  hosts: all

  vars:
    mygroups:
      - flintstones
      - rubbles

    myusers:
       fred:
          groups: flintstones
       wilma:
          groups: flintstones
       barney:
          groups: rubbles
       betty:
          groups: rubbles
  tasks:

    - name: Create groups
      group:
        name: "{{ item }}"
      loop: "{{ mygroups }}"

    - name: Create users in their appropriate groups
      user:
        name: "{{ item.key }}"
        groups: "{{ item.value.groups }}"
      loop: "{{ lookup('dict', myusers) }}"

