---
- name: Create users in the appropriate groups
  hosts: all
  become: true
  no_log: false

  tasks:

    - name: Ensure groups are created
      loop: "{{ mygroups }}"
      group:
        name: "{{ item }}"
        state: present

    - name: Ensure users are in their appropriate groups
      loop: "{{ lookup('dict', myusers) }}"
      user:
        name: "{{ item['key'] }}"
        groups: "{{ item['value']['groups'] }}"
        password: "{{ item['value']['password'] | password_hash('sha512') }}"
        update_password: on_create

