- name: Display the value of a variable called my_colour
  hosts: all
  become: false
  gather_facts: false

  vars:

    my_colour: blue
    
  vars_files:
    - my_variables.yml

  tasks:

    - name: Ensure fact controller learns about my_colour
      set_fact:
        my_colour: black
          
    - name: Ensure important variables are loaded
      ansible.builtin.include_vars:
        file: ink.yml

    - name: Print the value of the variable my_colour
      vars:
        my_colour: yellow
      ansible.builtin.debug:
        msg: The value of the variable is {{ my_colour }}
