- name: Print the value of variables
  hosts: all
  become: false
  gather_facts: false

  vars:

    my_colour: pink
      
  vars_files:

    - colours.yml

  tasks:

    - name: Load variables from external file
      ansible.builtin.include_vars:
        file: extra_colours.yml

    - name: Ensure the fact_controller learns
      ansible.builtin.set_fact:
        my_colour: black

    - name: Print the value of the variable my_colour
      vars:
        my_colour: purple
      ansible.builtin.debug:
        msg: The value of the variable my_colour is {{ my_colour }}

