- name: Print the value of variables
  hosts: all
  become: false
  gather_facts: false

  vars:

    my_colour: red

  vars_files:
    - colours.yml

  tasks:

    - name: Ensure fact controller learns
      ansible.builtin.set_fact:
        my_colour: green

    - name: Ensure variables are included
      ansible.builtin.include_vars:
        file: include_colours.yml

    - name: Print the value of the variable my_colour
      vars:
        my_colour: white
      ansible.builtin.debug:
        msg: The value of the variable my_colour is {{ my_colour | default('clear') }}

