- name: Fact delegation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Ensure fact is set
      ansible.builtin.set_fact:
        my_fact: I am a delegated fact
      delegate_to: servera
      delegate_facts: true

    - name: Ensure delegated host's fact is displayed
      ansible.builtin.debug:
        msg: "{{ hostvars['servera']['my_fact'] }}"

    - name: 'EXPECTED TO FAIL: Ensure fact is displayed from servera'
      ansible.builtin.debug:
        msg: "{{ my_fact }}"
