- name: Demonstrate bad use of loops
  hosts: "{{ my_host | mandatory('You must specify a host to target') }}"
  gather_facts: false
  become: true

  tasks:

    - name: "Good: Ensure that packages are at defined state"
      ansible.builtin.package:
        name:
        - bash
        - tmux
        - nmap
        - ant
        state: installed
