- name: Setup network at HPE
  hosts: servera
  become: true

  vars:

    network_connections:
      - name: static_net
        type: ethernet
        interface_name: eth1
        state: up
        ip:
          dhcp4: no
          address:
          - 192.168.0.1/24

  roles:
    - rhel-system-roles.network
