- name: Package facts
  hosts: "{{ my_host | default('localhost') }}"
  become: false
  gather_facts: true

  tasks: 

    - name: Ensure package facts are gathered
      register: my_facts
      ansible.builtin.package_facts:

    - name: Ensure facts are saved
      ansible.builtin.copy:
        content: "{{ my_facts }}"
        dest: /var/tmp/my_facts
        #        var: ansible_facts['packages'] | to_json
