- name: Populate users from a file
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Ensure user is at specified state
      vars:
        my_password: "{{ lookup('password', 'credentials/' + item + ' length=9') }}"
      loop: "{{ query('lines','cat users.txt') }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | password_hash('sha512') }}"
        update_password: on_create

          #    - name: Ensure text message is sent to user with password
          #      loop: "{{ query('lines','cat users.txt') }}"
          #      some_module:
          #        lookup('file', 'credentials/' + item)

        #    - name: Ensure password file is deleted
        #      ansible.builtin.file:
        #        file: "{{ lookup('file', 'credentials/' + item) }}"
        #       state: absent
