- name: Setup timesync
  hosts: all
  become: true

  vars:

    my_ntp: 0.rhel.pool.ntp.org 

    timesync_ntp_servers:
      - hostname: "{{ my_ntp }}" 

  roles:
    - redhat.rhel_system_roles.timesync
