- name: Configure Linux systems to use a tuned profile
  hosts: "{{ my_host }}"
  become: true
  gather_facts: true
  force_handlers: true

  tasks:

    - name: Ensure tuned is running
      tags:
        - always
      ansible.builtin.service:
        name: tuned
        state: started
        enabled: true

    - name: Determine current tuned profile
      tags:
        - always
      register: current_profile
      changed_when: false
      ansible.builtin.command: tuned-adm active

    - name: Ensure current profile is displayed
      tags:
        - always
      changed_when: false
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} currently uses the {{ current_profile['stdout'] }} profile"

    - name: Ensure current profile is saved
      tags:
        - set
      when: "my_profile not in current_profile['stdout']"
      ansible.builtin.copy:
        dest: /etc/tuned/saved_profile
        content: "{{ current_profile['stdout'] | regex_replace('Current active profile: ', '') }}"
        owner: root
        group: root
        mode: 0644
          
    - name: Set desired tuned profile
      register: set_profile
      tags:
        - set
      vars: 
        profile: "{{ my_profile | default('powersave') }}"
      when: "my_profile not in current_profile['stdout']"
      changed_when: "my_profile in set_profile['stdout']"
      ansible.builtin.command: tuned-adm profile {{ my_profile }}

    - name: Determine new tuned profile
      tags:
        - set
      register: new_profile
      changed_when: false
      ansible.builtin.command: tuned-adm active

    - name: Ensure profile is retrieved from saved config
      tags:
        - revert
      register: saved_profile
      ansible.builtin.slurp:
        src: /etc/tuned/saved_profile

    - name: Ensure profile is set from saved config
      tags:
        - revert
      when: "current_profile['stdout'] | regex_replace('Current active profile: ', '') != saved_profile | b64decode"
      changed_when: "saved_profile | b64decode in new_profile['stdout']"
      ansible.builtin.command: tuned-adm profile {{ saved_profile | b64decode }}

    - name: Ensure new profile is displayed
      tags:
        - always
      changed_when: false
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} currently uses the {{ new_profile['stdout'] | regex_replace('Current active profile: ', '') }} profile which was set on {{ ansible_facts['date_time']['iso8601'] }}"

