- name: Variables demonstration
  hosts: servera
  become: false
  gather_facts: false

  tasks:

    - name: Print the value of my_string
      ansible.builtin.debug:
        msg: The value of the variable my_string is {{ my_string }}
