- name: Ensure webservers are installed
  hosts: "{{ my_host | default('serverd') }}"
  become: true

  tasks:

    - name: Ensure software is managed
      ansible.builtin.dnf:
        name: "{{ my_webservice | default('httpd')}}"
        state: "{{ my_state | default('installed') }}"

    - name: Ensure webserver is configured with systemd
      ansible.builtin.service:
        name: "{{ my_webservice | default('httpd') }}"
        state: "{{ my_systemd_state | default('started') }}"
        enabled: "{{ my_systemd_enabled | default('true') }}"

    - name: Ensure port open in firewall
      ansible.posix.firewalld:
        service: "{{ my_fw_service | default('http') }}"
        state: "{{ my_fw_state | default('enabled') }}"
        permanent: "{{ my_fw_permanance | default('true') }}"
        immediate: "{{ my_fw_immediate | default('true') }}"

    - name: Ensure stub content is deployed
      ansible.builtin.copy:
        content: "{{ my_web_content | default('Hello world') }}"
        dest: /var/www/html/index.html

- name: Test webserver
  hosts: "{{ my_host | default('serverd') }}"
  become: false

  tasks:

    - name: Test {{ my_host | default('serverd') }}
      ansible.builtin.uri:
        url: http://{{ my_host | default('serverd') }}
        return_content: true
