- name: Update all software packages on RHEL systems
  hosts: all
  gather_facts: true
  become: true

  tasks:

    - name: Ensure dnf-utils is installed
      ansible.builtin.dnf:
        name: dnf-utils
        state: installed

    - name: Update software
      when: ansible_facts['distribution']  == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8
      ansible.builtin.dnf:
        name: "{{ my_package | default('*') }}"
        state: latest

    - name: Determine if reboot is necessary
      register: reboothint
      changed_when: false
      ignore_errors: true
      ansible.builtin.command: /usr/bin/dnf needs-restarting -r

    - name: Ensure server is rebooted
      when: reboothint['rc'] == 1
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Ensure that we can connect to server
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 600
