- name: Upgrade openSUSE 
  hosts: suse
  gather_facts: true
  become: true

  tasks:

    - name: Ensure zypper-needs-restarting is installed
      ansible.builtin.package:
        name: zypper-needs-restarting
        state: installed

    - name: Ensure distribution is upgraded
      register: dupout
      changed_when: "'changed' in dupout.stdout"
      when: ansible_facts['distribution']  == "openSUSE Leap" and ansible_facts['distribution_major_version'] | int >= 15
      ansible.builtin.command: /usr/bin/zypper --releasever={{ opensuse_version | default('15.4') }} dup -y

    - name: Determine if reboot is necessary
      register: reboothint
      ignore_errors: true
      ansible.builtin.command: /usr/bin/needs-restarting -r
      changed_when: false

    - name: Ensure server is rebooted
      when: reboothint['rc'] == 1
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Ensure that we can connect to server
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 600
