- name: Update all software packages on SUSE systems
  hosts: suse
  gather_facts: true
  become: true

  tasks:

    - name: Ensure zypper-needs-restarting is installed
      community.general.zypper: 
        name: zypper-needs-restarting
        state: installed

    - name: Update software
      when: ansible_facts['distribution']  == "openSUSE Leap" and ansible_facts['distribution_major_version'] | int >= 15
      community.general.zypper:
        name: "{{ my_package | default('*') }}"
        state: latest

    - name: Determine if reboot is necessary
      register: reboothint
      ignore_errors: true
      ansible.builtin.command: /usr/bin/needs-restarting -r
      changed_when: false

    - name: Ensure server is rebooted
      when: reboothint['rc'] == 1
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Ensure that we can connect to server
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 600
