---
- name: Set DNS records for IPA
  hosts: utility.lab.example.com

  vars:
    ipa_server: utility.lab.example.com
    ipa_admin: admin
    # Yes, we know that we should be using Ansible Vault here #dontjudge
    ipa_admin_pass: redhat321
    cicd_zones: 
      - blue.lab.example.io
      - green.lab.example.io

  tasks:

  - name: Create zones
    ipa_dnszone:
      ipa_host: "{{ ipa_server }}"
      ipa_user: "{{ ipa_admin }}"
      ipa_pass: "{{ ipa_admin_pass }}"
      zone_name: "{{ item }}"
      state: present
    loop: "{{ cicd_zones }}"
...
