main: 
  label: 'FreeIPA'
  host: 'utility.lab.example.com'
  port: 389
  uid: 'uid'
  method: 'tls'
  bind_dn: 'uid=git,cn=users,cn=accounts,dc=example,dc=com'
  password: 'redhat321'
  encryption: 'plain'
  base: 'cn=accounts,dc=example,dc=com'
  verify_certificates: false
  attributes:
    username: ['uid']
    email: ['mail']
    name: 'displayName'
    first_name: 'givenName'
    last_name: 'sn'
