- name: Create needed user accounts in IDM to be used by GitLab
  hosts: utility.lab.example.com
  vars:
    ipa_server: utility.lab.example.com
    ipa_admin_user: admin
    # Yes, we know that we should be using Ansible Vault #dontjudge
    ipa_admin_pass: redhat321
    users:
      git:
        givenname: Git
        sn: Lab
        pass: redhat321
      student:
        givenname: Student
        sn: User
        pass: student
   
  tasks:

    - name: Create GitLab user in FreeIPA for integration
      ipa_user:
        name: "{{ item.key }}"
        password: "{{ item.value.pass }}"
        givenname: "{{ item.value.givenname }}"
        sn: "{{ item.value.sn }}"
        state: present
        ipa_host: "{{ ipa_server }}"
        ipa_user: "{{ ipa_admin_user }}"
        ipa_pass: "{{ ipa_admin_pass }}"
        krbpasswordexpiration: "20300404235959"
      with_dict:
        - "{{ users }}" 

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure

