#!/bin/bash
#
# Copyright 2018 Red Hat, Inc.
#
# NAME
#     demo-idm-install - grading script for RH362 IdM Install Demo
#
# SYNOPSIS
#     demo-idm-install {setup|grade|cleanup|solve}
#
#        setup   - prepare the system for starting the lab
#        cleanup - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, or
#     cleanup for the IdM Install Demo.
#
# CHANGELOG
#   * Wed Feb 21 2018 Chen Chang <cchang@redhat.com>
#   - original code

#########################################################################

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='idm'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup)

function lab_setup {

  print_header "Setting up ${target} for demo exercise work:"
  host_reachable ${target}


  # Check for demo prerequisites
  CMD="rpm -q ipa-server"
  if ! ${ssh} ${target} "${CMD}"
  then
    if ! rpm -q ansible
    then
      pad ' · Installing ansible'
      yum install -y http://materials.example.com/classroom/ansible/ansible-2.5.0-0.0.devel.201801312256git.512d6f6ac6.el7.ans.noarch.rpm && mkdir /home/student/ansible
      if [ $? -eq 0 ]
      then
        print_SUCCESS
      else
        print_FAIL
      fi
    fi
  
    pad ' · Installing IPA server prerequisites on idm host'
    cd /home/student/ansible && curl -O http://materials.example.com/classroom/ansible/ansible.cfg && curl -O http://materials.example.com/classroom/ansible/inventory && curl -O http://materials.example.com/classroom/ansible/install_ipa_server_basic.yml && ansible-playbook install_ipa_server_basic.yml --skip-tags=ipactl,ipa-server-install,kinit
    if [ $? -eq 0 ]
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    pad " · ipa-server package is installed on ${target}"
    print_PASS
  fi
  
  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
