#!/bin/bash
#
# Copyright 2018 Red Hat, Inc.
#
# NAME
#     lab-review-topology - grading script for RH362 topology review lab
# SYNOPSIS
#     lab-review-topology {setup|grade}
#
#
# DESCRIPTION
#     This script, based on singular argument, it does setup, and grade, for the topology review LAB.
#
# CHANGELOG
#   * Wed May 23 2018 Chen Chang <cchang@redhat.com>
#   - original code
PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='workstation'
target2='replica1'
target3='idm'
target4='client'
directory='/home/student/ansible'
package='ipa-client'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup grade)


function lab_setup {

  print_header "Setting up ${target} for lab exercise work:"
  host_reachable ${target3}

   #temp fix
   ${ssh} ${target2} chattr -i /etc/sysconfig/network-scripts/ifcfg-eth0

    if ! rpm -q ansible
    then
      pad ' · Installing ansible'
      yum install -y http://materials.example.com/classroom/ansible/ansible-2.5.0-0.0.devel.201801312256git.512d6f6ac6.el7.ans.noarch.rpm && mkdir /home/student/ansible
      if [ $? -eq 0 ]
      then
        print_SUCCESS
      else
        print_FAIL
      fi
    fi

    if [ ! -d "$directory" ];
    then
      pad ' · Creating directory'
      mkdir $directory && chown -R student:student $directory
      if [ $? -eq 0 ]
      then
        print_SUCCESS
      else
        print_FAIL
      fi
    fi

    pad ' . Downloading files from classroom server'
    cd /home/student/ansible && wget --no-parent -r -nH --reject="index.html*" --cut-dirs=2 http://materials.example.com/classroom/ansible/ && chown -R student:student /home/student/ansible
    if [ $? -eq 0 ]
    then
      print_SUCCESS
    else
      print_FAIL
    fi

    if ! rpm -q python2-winrm
    then
      pad ' · Installing python modules'
      cd $directory && rpm -ivh python2-winrm-0.2.2-1.el7.noarch.rpm python2-ntlm3-1.0.2-1.el7.noarch.rpm python2-requests_ntlm-0.3.0-1.el7.noarch.rpm python-xmltodict-0.9.0-1.el7.noarch.rpm
      if [ $? -eq 0 ]
      then
        print_SUCCESS
      else
        print_FAIL
      fi
    fi

    pad ' . Configuring network on replica1'
    if cd /home/student/ansible && ansible-playbook network.yml --extra-vars "server=replica1.lab.example.net --extra-vars ip=172.25.250.9/24"
    then
      print_SUCCESS
    else
      print_FAIL
    fi

    pad ' · Registering replica1'
    CMD='rpm -q ipa-client'
    if ${ssh} ${target2} "${CMD}"
    then
      print_SUCCESS
    else
      cd /home/student/ansible && ansible-playbook install_ipa_client.yml --extra-vars "ipa_client=replica1.lab.example.net"
      print_SUCCESS
    fi
}

function lab_grade {
  print_header "Grading the student's work:"
  host_reachable ${target3}
  host_reachable ${target4}

  pad ' . Verifying replica1 status'
  CMD='ipa topologysegment-find domain|grep replica1'
  if ${ssh} ${target3} "${CMD}"
  then
    print_PASS
  else
    print_FAIL
  fi

  pad " · Ensuring ${package} is installed"
  if ${ssh} ${target4} yum list installed ${package}; then
    print_PASS
  else
    print_FAIL
  fi

  pad " · Checking DNS settings"
  if ${ssh} ${target4} "nmcli connection show 'System eth0'" | grep "ipv4.dns:".*${idm_dns}; then
    print_PASS
  else
    print_FAIL
  fi

  pad " · Checking Kerberos authentication"
  if ${ssh} ${target4} "echo RedHat123^ | kinit admin"; then
    print_PASS
  else
    print_FAIL
  fi

  # Overall grade
  print_line
  pad 'Overall lab grade'
  if [[ ${fail_count} -eq 0 ]]
  then
    print_PASS
  else
    print_FAIL
  fi
}



############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
