#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-products-satellite - grading script for RH362 products-satellite GE
#
# SYNOPSIS
#     lab-products-satellite {setup}
#
#        setup   - prepare the system for starting the lab
#        grade   - perform evaluation steps on the system
#        cleanup - perform post-lab cleanup
#        solve   - do the lab exercise for the student (may call setup)
#        (ONLY INCLUDE PROVIDED COMMANDS, REMOVE REST)
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve.
#
# CHANGELOG
#   * Thu Apr 11 2018 Chen Chang <cchang@redhat.com>
#   - original code
#########################################################################
#########################################################################

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
sattarget='satellite.lab.example.net'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup cleanup)


function lab_setup {
  print_header "Setting up ${sattarget} for lab exercise work:"
  host_reachable ${sattarget}

  # Restart Katello
  pad ' · Restarting Katello'
  CMD="katello-service restart"
  if ${ssh} ${sattarget} "${CMD}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi
}

function lab_cleanup {
  target=${workstationtarget}

  print_header "Cleaning up the lab on ${target}:"

  # Nothing to do
  pad ' . Cleaning lab files'
  print_SUCCESS

  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"


