---
- name: Setup the support infrastructure to manage systems
  hosts: all 
  tasks:
  
    - name: Create the user support as a member of the group wheel
      user:
        groups: wheel
        name: support

    - name: Install the sudo configuration which allows passwordless execution of commands as root
      copy:
        src: support.sudo
        dest: /etc/sudoers.d/support

    - name: Install the ssh key
      authorized_key:
        manage_dir: yes
        user: support
        key: "{{ lookup('file', 'id_rsa.pub') }}" 

    - name: Limit ssh usage to members of the group wheel
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
      notify: Restart the ssh daemon
      
  handlers:

    - name: Restart the ssh daemon
      service:
        name: sshd
        state: restarted
...
