#!/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-library-test-harness - contains tests for library functions
#
# SYNOPSIS
#     lab-library-test-harness run
#
#        run     - run the currently enabled tests
#
# DESCRIPTION
#     This script is used to test new library functions
#     and can be viewed to see function calling examples
#
# CHANGELOG
#   * Thu Feb 13 2018 Morgan Weetman <mweetman@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(run)


function lab_run {

  print_header "Testing library functions:"

  #pad ' . Checking the IdM services status: '
  #if idm_service_status
  #then
  #  print_SUCCESS
  #else
  #  print_FAIL
  #fi

  #pad ' . Ensuring IdM services are ready: '
  #if idm_service_ready
  #then
  #  print_SUCCESS
  #else
  #  print_FAIL
  #fi

  #idm_base_state no_users

  #idm_base_state

  #idm_ad_trust


  print_line
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
