- name: Setup nbde servers
  hosts: 
    - serverb
    - serverc
    - serverd
  become: true
  gather_facts: false

  vars:
    nbde_server_rotate_keys: true
    nbde_server_manage_firewall: true
    nbde_server_manage_selinux: true

  roles:
    - rhel-system-roles.nbde_server

